# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: rili <marvin@42.fr>                        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/03/29 19:08:48 by rili              #+#    #+#              #
#    Updated: 2017/03/29 20:56:29 by rili             ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
FLAG = -Wall -Werror -Wextra
SRC = ft_display_file.c
OBJ = ft_display_file.o

all: $(NAME)

$(NAME):
		gcc -o $(NAME) $(SRC) $(FLAG)

clean:
	/bin/rm -f $(OBJ)

fclean:
	/bin/rm -f $(NAME)

re: fclean all

